package cluster

import "testing"

// Oracle provenance (recorded for audit; see hash.go for the algorithm pins):
//
//   xxHash64 (XXH64, seed 0): vectors generated by github.com/cespare/xxhash/v2
//   v2.3.0 (from the Go module cache, in a throwaway /tmp/xxoracle module NEVER
//   imported by repo code). The canonical empty-input vector
//   xxHash64("") == 0xEF46DB3751D8E999 is the published XXH64 reference value
//   and was confirmed to match the oracle before trusting its other outputs.
//
//   murmurHash2 (MurmurHash64A, seed 0xc70f6907): vector generated by compiling
//   Austin Appleby's canonical public-domain MurmurHash64A C reference
//   (MurmurHash2.cpp, m=0xc6a4a7935bd1e995, r=47) with gcc and emitting the
//   value for the representative ring key. MURMUR_HASH_2 is unit-level only per
//   SPEC §2 (no differential/live-reference cross-check on this path).
//
// Pinned vectors (input -> hex):
//   xxHash64("")                                                     == 0xef46db3751d8e999
//   xxHash64("127.0.0.1:9001_0")                                     == 0x3eee954d5ec5315f
//   xxHash64("127.0.0.2")                                            == 0xda3057a00712c3b3
//   xxHash64("abc")                                                  == 0x44bc2cf5ad770999
//   xxHash64("the quick brown fox jumps over the lazy dog 0123456789") == 0xb98d13125e00e1fb (54 bytes)
//   murmurHash2("127.0.0.1:9001_0", 0xc70f6907)                      == 0xc2a19fe5a9c77221

func TestXXHash64_PublishedVectors(t *testing.T) {
	cases := []struct {
		in   string
		want uint64
	}{
		{"", 0xEF46DB3751D8E999},
		{"127.0.0.1:9001_0", 0x3eee954d5ec5315f},
		{"127.0.0.2", 0xda3057a00712c3b3},
		{"abc", 0x44bc2cf5ad770999},
	}
	for _, c := range cases {
		if got := xxHash64([]byte(c.in)); got != c.want {
			t.Errorf("xxHash64(%q) = %#016x, want %#016x", c.in, got, c.want)
		}
	}
}

func TestXXHash64_LongInputStripeLoop(t *testing.T) {
	in := "the quick brown fox jumps over the lazy dog 0123456789" // 54 bytes
	const want uint64 = 0xb98d13125e00e1fb
	if got := xxHash64([]byte(in)); got != want {
		t.Errorf("xxHash64(long) = %#016x, want %#016x", got, want)
	}
}

func TestMurmurHash2_PinnedVector(t *testing.T) {
	const seed uint64 = 0xc70f6907
	const want uint64 = 0xc2a19fe5a9c77221
	if got := murmurHash2([]byte("127.0.0.1:9001_0"), seed); got != want {
		t.Errorf("murmurHash2 = %#016x, want %#016x", got, want)
	}
}

func TestIpOnly(t *testing.T) {
	cases := map[string]string{
		"127.0.0.2:57735": "127.0.0.2",
		"[::1]:443":       "::1",
		"127.0.0.2":       "127.0.0.2", // already bare → unchanged
	}
	for in, want := range cases {
		if got := ipOnly(in); got != want {
			t.Errorf("ipOnly(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestHashHeaderValues(t *testing.T) {
	// Single value collapses to xxHash64([]byte(value)) (the fixture path).
	if got, want := HashHeaderValues([]string{"alpha"}), xxHash64([]byte("alpha")); got != want {
		t.Fatalf("single-value: got %#x want %#x", got, want)
	}
	// Empty list → 0 (caller treats the contribution as "no value"; applyHashKey
	// only calls this when the header is present, so this is a defensive pin).
	if got := HashHeaderValues(nil); got != 0 {
		t.Fatalf("empty: got %#x want 0", got)
	}
	// Seed-chained over BYTE-SORTED values: XXH64("b", XXH64("a", 0)).
	want := xxHash64Seed([]byte("b"), xxHash64Seed([]byte("a"), 0))
	if got := HashHeaderValues([]string{"b", "a"}); got != want { // input unsorted → sorted internally
		t.Fatalf("multi-value: got %#x want %#x", got, want)
	}
	// Sort is byte-wise: {"a","b"} and {"b","a"} produce the SAME key.
	if HashHeaderValues([]string{"a", "b"}) != HashHeaderValues([]string{"b", "a"}) {
		t.Fatal("multi-value fold must be sort-order-independent")
	}
}

func TestHashSourceIP_StripsPort(t *testing.T) {
	// The key must depend ONLY on the IP, not the ephemeral port: two different
	// ports from the same client IP yield the SAME key (the affinity property).
	a := HashSourceIP("127.0.0.2:57735")
	b := HashSourceIP("127.0.0.2:40001")
	if a != b {
		t.Errorf("HashSourceIP must ignore the port: %#x != %#x", a, b)
	}
	// And it equals xxHash64 of the bare IP (the documented contract).
	if a != xxHash64([]byte("127.0.0.2")) {
		t.Errorf("HashSourceIP(127.0.0.2:port) = %#x, want xxHash64(\"127.0.0.2\")=%#x", a, xxHash64([]byte("127.0.0.2")))
	}
}
